spring.application.name=gestion-voyage
# Server port
server.port=8080

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_voyage
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=njahrojo292@gmail.com
spring.mail.password=adnhxzwbtdkbysiv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
stripe.secret.key=pk_test_51R2028C2mfDV0x0O5VZE9WBXKJoIiFv7A2IAVrKlzacMdKUMx5wv7qC8WZAYLtmF3i6EqPxf4qpGIwnPLxO5vc8F004k41lTWO

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect